"""Declarative base and shared column helpers.

Two decisions live here and apply to every table.

**Naming convention.** Alembic compares the database against these models to
generate migrations. Without an explicit convention, Postgres invents index and
constraint names, and autogenerate then proposes dropping and recreating things
that never changed. The convention makes names deterministic.

**Schema.** Every table is placed in the configured schema (`gridmind`), not
`public`, so the read-only role's `search_path` finds exactly our tables and
nothing else.
"""

from __future__ import annotations

import datetime as dt
from enum import StrEnum

from sqlalchemy import BigInteger, DateTime, Enum, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: Kept in sync with `Settings.database_schema`, which validates the name.
SCHEMA = "gridmind"

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(schema=SCHEMA, naming_convention=NAMING_CONVENTION)


def pg_enum(enum_cls: type[StrEnum], name: str) -> Enum:
    """A native Postgres enum whose labels are the enum *values*.

    `values_callable` is not optional here. SQLAlchemy defaults to using member
    **names**, which would create a type with labels `PRACTICE_1` and `RACE`
    while the application and the frontend send `practice_1` and `race`. The
    mismatch has no compile-time symptom — it surfaces as an invalid-input
    error on the first insert, or worse, as a type that silently disagrees with
    the wire contract.

    `inherit_schema` is equally necessary. Without it the type is created
    unqualified, which puts it in `public` — outside the schema the read-only
    role can see. Reading such a column happens to work, but any SQL naming the
    type fails:

        select 'race'::session_type
        -> type "session_type" does not exist

    The agent writes its own SQL, so a cast it emits must resolve.
    """
    return Enum(
        enum_cls,
        name=name,
        native_enum=True,
        inherit_schema=True,
        values_callable=lambda cls: [member.value for member in cls],
    )


def pk() -> Mapped[int]:
    """Surrogate primary key.

    BigInteger because `laps` grows fastest: roughly 20 drivers x 60 laps per
    race session, and every session ever asked about is kept permanently.
    """
    return mapped_column(BigInteger, primary_key=True, autoincrement=True)


def utc_now() -> Mapped[dt.datetime]:
    """Server-side timestamp.

    Generated by Postgres rather than Python so that rows written by a script,
    a migration or the API all agree on the clock.
    """
    return mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
