"""initial schema

Revision ID: fe633526d1b1
Revises:
Create Date: 2026-09-23 11:56:40.431510

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fe633526d1b1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "circuits",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("circuit_key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("location", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_circuits")),
        sa.UniqueConstraint("circuit_key", name=op.f("uq_circuits_circuit_key")),
        schema="gridmind",
    )
    op.create_table(
        "constructors",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("constructor_ref", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("nationality", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_constructors")),
        sa.UniqueConstraint("constructor_ref", name=op.f("uq_constructors_constructor_ref")),
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_constructors_name"), "constructors", ["name"], unique=False, schema="gridmind"
    )
    op.create_table(
        "drivers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("driver_code", sa.String(length=8), nullable=True),
        sa.Column("driver_ref", sa.String(length=64), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("full_name", sa.String(length=128), nullable=False),
        sa.Column("nationality", sa.String(length=64), nullable=True),
        sa.Column("permanent_number", sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drivers")),
        sa.UniqueConstraint("driver_ref", name=op.f("uq_drivers_driver_ref")),
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_drivers_driver_code"), "drivers", ["driver_code"], unique=False, schema="gridmind"
    )
    op.create_index(
        op.f("ix_drivers_full_name"), "drivers", ["full_name"], unique=False, schema="gridmind"
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("season_year", sa.SmallInteger(), nullable=False),
        sa.Column("round_number", sa.SmallInteger(), nullable=False),
        sa.Column(
            "session_type",
            sa.Enum(
                "practice_1",
                "practice_2",
                "practice_3",
                "qualifying",
                "sprint",
                "sprint_qualifying",
                "race",
                name="session_type",
                schema="gridmind",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "skipped_cached",
                name="job_status",
                schema="gridmind",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "resolving",
                "fetching",
                "storing",
                "verifying",
                "answering",
                name="job_stage",
                schema="gridmind",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column("progress_percent", sa.SmallInteger(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("rows_written", sa.Integer(), nullable=True),
        sa.Column("requested_by_conversation_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
        schema="gridmind",
    )
    op.create_index(
        "ix_ingestion_jobs_season_year_round_number_session_type",
        "ingestion_jobs",
        ["season_year", "round_number", "session_type"],
        unique=False,
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_ingestion_jobs_status"),
        "ingestion_jobs",
        ["status"],
        unique=False,
        schema="gridmind",
    )
    op.create_index(
        "uq_ingestion_jobs_active",
        "ingestion_jobs",
        ["season_year", "round_number", "session_type"],
        unique=True,
        schema="gridmind",
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint("year", name=op.f("uq_seasons_year")),
        schema="gridmind",
    )
    op.create_table(
        "constructor_standings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("constructor_id", sa.BigInteger(), nullable=False),
        sa.Column("round_number", sa.SmallInteger(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=True),
        sa.Column("points", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("wins", sa.SmallInteger(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["constructor_id"],
            ["gridmind.constructors.id"],
            name=op.f("fk_constructor_standings_constructor_id_constructors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["gridmind.seasons.id"],
            name=op.f("fk_constructor_standings_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_constructor_standings")),
        sa.UniqueConstraint(
            "season_id",
            "round_number",
            "constructor_id",
            name=op.f("uq_constructor_standings_season_id_round_number_constructor_id"),
        ),
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_constructor_standings_constructor_id"),
        "constructor_standings",
        ["constructor_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_constructor_standings_season_id"),
        "constructor_standings",
        ["season_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_table(
        "driver_seasons",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("driver_id", sa.BigInteger(), nullable=False),
        sa.Column("constructor_id", sa.BigInteger(), nullable=False),
        sa.Column("car_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["constructor_id"],
            ["gridmind.constructors.id"],
            name=op.f("fk_driver_seasons_constructor_id_constructors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["gridmind.drivers.id"],
            name=op.f("fk_driver_seasons_driver_id_drivers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["gridmind.seasons.id"],
            name=op.f("fk_driver_seasons_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_driver_seasons")),
        sa.UniqueConstraint(
            "season_id",
            "driver_id",
            "constructor_id",
            name=op.f("uq_driver_seasons_season_id_driver_id_constructor_id"),
        ),
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_driver_seasons_constructor_id"),
        "driver_seasons",
        ["constructor_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_driver_seasons_driver_id"),
        "driver_seasons",
        ["driver_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_driver_seasons_season_id"),
        "driver_seasons",
        ["season_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_table(
        "driver_standings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("driver_id", sa.BigInteger(), nullable=False),
        sa.Column("constructor_id", sa.BigInteger(), nullable=True),
        sa.Column("round_number", sa.SmallInteger(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=True),
        sa.Column("points", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("wins", sa.SmallInteger(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["constructor_id"],
            ["gridmind.constructors.id"],
            name=op.f("fk_driver_standings_constructor_id_constructors"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["gridmind.drivers.id"],
            name=op.f("fk_driver_standings_driver_id_drivers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["gridmind.seasons.id"],
            name=op.f("fk_driver_standings_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_driver_standings")),
        sa.UniqueConstraint(
            "season_id",
            "round_number",
            "driver_id",
            name=op.f("uq_driver_standings_season_id_round_number_driver_id"),
        ),
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_driver_standings_constructor_id"),
        "driver_standings",
        ["constructor_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_driver_standings_driver_id"),
        "driver_standings",
        ["driver_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_driver_standings_season_id"),
        "driver_standings",
        ["season_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_table(
        "meetings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("circuit_id", sa.BigInteger(), nullable=True),
        sa.Column("round_number", sa.SmallInteger(), nullable=False),
        sa.Column("event_name", sa.String(length=160), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["circuit_id"],
            ["gridmind.circuits.id"],
            name=op.f("fk_meetings_circuit_id_circuits"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["gridmind.seasons.id"],
            name=op.f("fk_meetings_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
        sa.UniqueConstraint(
            "season_id", "round_number", name=op.f("uq_meetings_season_id_round_number")
        ),
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_meetings_circuit_id"), "meetings", ["circuit_id"], unique=False, schema="gridmind"
    )
    op.create_index(
        "ix_meetings_event_date", "meetings", ["event_date"], unique=False, schema="gridmind"
    )
    op.create_index(
        op.f("ix_meetings_season_id"), "meetings", ["season_id"], unique=False, schema="gridmind"
    )
    op.create_table(
        "standings_fetches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("round_number", sa.SmallInteger(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["gridmind.seasons.id"],
            name=op.f("fk_standings_fetches_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_standings_fetches")),
        sa.UniqueConstraint(
            "season_id", "round_number", name=op.f("uq_standings_fetches_season_id_round_number")
        ),
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_standings_fetches_season_id"),
        "standings_fetches",
        ["season_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "report_type",
            sa.Enum("summary", "full", name="report_type", schema="gridmind", inherit_schema=True),
            nullable=False,
        ),
        sa.Column(
            "trigger",
            sa.Enum(
                "automatic",
                "on_request",
                name="report_trigger",
                schema="gridmind",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["gridmind.meetings.id"],
            name=op.f("fk_reports_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint(
            "meeting_id", "report_type", name=op.f("uq_reports_meeting_id_report_type")
        ),
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_reports_meeting_id"), "reports", ["meeting_id"], unique=False, schema="gridmind"
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "session_type",
            sa.Enum(
                "practice_1",
                "practice_2",
                "practice_3",
                "qualifying",
                "sprint",
                "sprint_qualifying",
                "race",
                name="session_type",
                schema="gridmind",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column("session_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["gridmind.meetings.id"],
            name=op.f("fk_sessions_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint(
            "meeting_id", "session_type", name=op.f("uq_sessions_meeting_id_session_type")
        ),
        schema="gridmind",
    )
    op.create_index(
        "ix_sessions_ingested_at", "sessions", ["ingested_at"], unique=False, schema="gridmind"
    )
    op.create_index(
        op.f("ix_sessions_meeting_id"), "sessions", ["meeting_id"], unique=False, schema="gridmind"
    )
    op.create_table(
        "laps",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("driver_id", sa.BigInteger(), nullable=False),
        sa.Column("lap_number", sa.SmallInteger(), nullable=False),
        sa.Column("lap_time_ms", sa.Integer(), nullable=True),
        sa.Column("sector_1_ms", sa.Integer(), nullable=True),
        sa.Column("sector_2_ms", sa.Integer(), nullable=True),
        sa.Column("sector_3_ms", sa.Integer(), nullable=True),
        sa.Column("speed_trap_kph", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("position", sa.SmallInteger(), nullable=True),
        sa.Column("compound", sa.String(length=16), nullable=True),
        sa.Column("tyre_life", sa.SmallInteger(), nullable=True),
        sa.Column("is_personal_best", sa.Boolean(), nullable=True),
        sa.Column("track_status", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["gridmind.drivers.id"],
            name=op.f("fk_laps_driver_id_drivers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["gridmind.sessions.id"],
            name=op.f("fk_laps_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_laps")),
        sa.UniqueConstraint(
            "session_id",
            "driver_id",
            "lap_number",
            name=op.f("uq_laps_session_id_driver_id_lap_number"),
        ),
        schema="gridmind",
    )
    op.create_index(op.f("ix_laps_compound"), "laps", ["compound"], unique=False, schema="gridmind")
    op.create_index(
        op.f("ix_laps_driver_id"), "laps", ["driver_id"], unique=False, schema="gridmind"
    )
    op.create_index(
        op.f("ix_laps_session_id"), "laps", ["session_id"], unique=False, schema="gridmind"
    )
    op.create_index(
        "ix_laps_session_id_driver_id_lap_number",
        "laps",
        ["session_id", "driver_id", "lap_number"],
        unique=False,
        schema="gridmind",
    )
    op.create_table(
        "pit_stops",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("driver_id", sa.BigInteger(), nullable=False),
        sa.Column("stop_number", sa.SmallInteger(), nullable=False),
        sa.Column("lap_number", sa.SmallInteger(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["gridmind.drivers.id"],
            name=op.f("fk_pit_stops_driver_id_drivers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["gridmind.sessions.id"],
            name=op.f("fk_pit_stops_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pit_stops")),
        sa.UniqueConstraint(
            "session_id",
            "driver_id",
            "stop_number",
            name=op.f("uq_pit_stops_session_id_driver_id_stop_number"),
        ),
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_pit_stops_driver_id"), "pit_stops", ["driver_id"], unique=False, schema="gridmind"
    )
    op.create_index(
        op.f("ix_pit_stops_session_id"),
        "pit_stops",
        ["session_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_table(
        "race_control_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("driver_id", sa.BigInteger(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lap_number", sa.SmallInteger(), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("flag", sa.String(length=32), nullable=True),
        sa.Column("scope", sa.String(length=32), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["gridmind.drivers.id"],
            name=op.f("fk_race_control_events_driver_id_drivers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["gridmind.sessions.id"],
            name=op.f("fk_race_control_events_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_race_control_events")),
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_race_control_events_driver_id"),
        "race_control_events",
        ["driver_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_race_control_events_session_id"),
        "race_control_events",
        ["session_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_index(
        "ix_race_control_events_session_id_timestamp",
        "race_control_events",
        ["session_id", "timestamp"],
        unique=False,
        schema="gridmind",
    )
    op.create_table(
        "session_results",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("driver_id", sa.BigInteger(), nullable=False),
        sa.Column("constructor_id", sa.BigInteger(), nullable=True),
        sa.Column("position", sa.SmallInteger(), nullable=True),
        sa.Column("grid_position", sa.SmallInteger(), nullable=True),
        sa.Column("points", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.Column("total_laps", sa.SmallInteger(), nullable=True),
        sa.Column("fastest_lap", sa.Boolean(), nullable=False),
        sa.Column("fastest_lap_time_ms", sa.Integer(), nullable=True),
        sa.Column("q1_time_ms", sa.Integer(), nullable=True),
        sa.Column("q2_time_ms", sa.Integer(), nullable=True),
        sa.Column("q3_time_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["constructor_id"],
            ["gridmind.constructors.id"],
            name=op.f("fk_session_results_constructor_id_constructors"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["gridmind.drivers.id"],
            name=op.f("fk_session_results_driver_id_drivers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["gridmind.sessions.id"],
            name=op.f("fk_session_results_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_results")),
        sa.UniqueConstraint(
            "session_id", "driver_id", name=op.f("uq_session_results_session_id_driver_id")
        ),
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_session_results_constructor_id"),
        "session_results",
        ["constructor_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_session_results_driver_id"),
        "session_results",
        ["driver_id"],
        unique=False,
        schema="gridmind",
    )
    op.create_index(
        op.f("ix_session_results_session_id"),
        "session_results",
        ["session_id"],
        unique=False,
        schema="gridmind",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_session_results_session_id"), table_name="session_results", schema="gridmind"
    )
    op.drop_index(
        op.f("ix_session_results_driver_id"), table_name="session_results", schema="gridmind"
    )
    op.drop_index(
        op.f("ix_session_results_constructor_id"), table_name="session_results", schema="gridmind"
    )
    op.drop_table("session_results", schema="gridmind")
    op.drop_index(
        "ix_race_control_events_session_id_timestamp",
        table_name="race_control_events",
        schema="gridmind",
    )
    op.drop_index(
        op.f("ix_race_control_events_session_id"),
        table_name="race_control_events",
        schema="gridmind",
    )
    op.drop_index(
        op.f("ix_race_control_events_driver_id"),
        table_name="race_control_events",
        schema="gridmind",
    )
    op.drop_table("race_control_events", schema="gridmind")
    op.drop_index(op.f("ix_pit_stops_session_id"), table_name="pit_stops", schema="gridmind")
    op.drop_index(op.f("ix_pit_stops_driver_id"), table_name="pit_stops", schema="gridmind")
    op.drop_table("pit_stops", schema="gridmind")
    op.drop_index("ix_laps_session_id_driver_id_lap_number", table_name="laps", schema="gridmind")
    op.drop_index(op.f("ix_laps_session_id"), table_name="laps", schema="gridmind")
    op.drop_index(op.f("ix_laps_driver_id"), table_name="laps", schema="gridmind")
    op.drop_index(op.f("ix_laps_compound"), table_name="laps", schema="gridmind")
    op.drop_table("laps", schema="gridmind")
    op.drop_index(op.f("ix_sessions_meeting_id"), table_name="sessions", schema="gridmind")
    op.drop_index("ix_sessions_ingested_at", table_name="sessions", schema="gridmind")
    op.drop_table("sessions", schema="gridmind")
    op.drop_index(op.f("ix_reports_meeting_id"), table_name="reports", schema="gridmind")
    op.drop_table("reports", schema="gridmind")
    op.drop_index(
        op.f("ix_standings_fetches_season_id"), table_name="standings_fetches", schema="gridmind"
    )
    op.drop_table("standings_fetches", schema="gridmind")
    op.drop_index(op.f("ix_meetings_season_id"), table_name="meetings", schema="gridmind")
    op.drop_index("ix_meetings_event_date", table_name="meetings", schema="gridmind")
    op.drop_index(op.f("ix_meetings_circuit_id"), table_name="meetings", schema="gridmind")
    op.drop_table("meetings", schema="gridmind")
    op.drop_index(
        op.f("ix_driver_standings_season_id"), table_name="driver_standings", schema="gridmind"
    )
    op.drop_index(
        op.f("ix_driver_standings_driver_id"), table_name="driver_standings", schema="gridmind"
    )
    op.drop_index(
        op.f("ix_driver_standings_constructor_id"), table_name="driver_standings", schema="gridmind"
    )
    op.drop_table("driver_standings", schema="gridmind")
    op.drop_index(
        op.f("ix_driver_seasons_season_id"), table_name="driver_seasons", schema="gridmind"
    )
    op.drop_index(
        op.f("ix_driver_seasons_driver_id"), table_name="driver_seasons", schema="gridmind"
    )
    op.drop_index(
        op.f("ix_driver_seasons_constructor_id"), table_name="driver_seasons", schema="gridmind"
    )
    op.drop_table("driver_seasons", schema="gridmind")
    op.drop_index(
        op.f("ix_constructor_standings_season_id"),
        table_name="constructor_standings",
        schema="gridmind",
    )
    op.drop_index(
        op.f("ix_constructor_standings_constructor_id"),
        table_name="constructor_standings",
        schema="gridmind",
    )
    op.drop_table("constructor_standings", schema="gridmind")
    op.drop_table("seasons", schema="gridmind")
    op.drop_index(
        "uq_ingestion_jobs_active",
        table_name="ingestion_jobs",
        schema="gridmind",
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.drop_index(op.f("ix_ingestion_jobs_status"), table_name="ingestion_jobs", schema="gridmind")
    op.drop_index(
        "ix_ingestion_jobs_season_year_round_number_session_type",
        table_name="ingestion_jobs",
        schema="gridmind",
    )
    op.drop_table("ingestion_jobs", schema="gridmind")
    op.drop_index(op.f("ix_drivers_full_name"), table_name="drivers", schema="gridmind")
    op.drop_index(op.f("ix_drivers_driver_code"), table_name="drivers", schema="gridmind")
    op.drop_table("drivers", schema="gridmind")
    op.drop_index(op.f("ix_constructors_name"), table_name="constructors", schema="gridmind")
    op.drop_table("constructors", schema="gridmind")
    op.drop_table("circuits", schema="gridmind")
    # ### end Alembic commands ###
